#!/usr/bin/env bash

set -eu

script_path="$(dirname "$(realpath "${0}")")"
mode="none"
output="-"
file=""
section=""
param=""
value=""
version="0.1"
stdin=false

_usage () {
    echo "A utility for manipulating ini files"
    echo
    echo "Usage: crshini --set   [OPTION]... file section   [param] [value]"
    echo "       crshini --get   [OPTION]... file [section] [param]"
    echo "       crshini --merge [OPTION]... file [section]"
    echo
    echo "Options:"
    echo "       -h | --help      Show this help message"
    echo "            --version   Show version info and exit"
    echo "            --optput    Set the output path ( - means stdout)"
    echo "            --stdin     Use stdin instead of file (--merge is always true)"

}

_version(){
    echo "[frontend]"
    echo "Name=crshini"
    echo "Version=${version}"
    echo "Path=$(realpath "${0}")"
    echo
    echo "[library]"
    echo "Name=libcrshini"
    echo "Version=${_crshini_version}"
    echo "Path=${libcrshini}"
}

# Find libcrshini
libcrshini_list=("${script_path}/libcrshini" "/lib/libcrshini")
for libcrshini in "${libcrshini_list[@]}"; do
    [[ -f "${libcrshini}" ]] && source "${libcrshini}" && break
done

# Parse options
ARGUMENT=("${@}")
OPTS=("h")
OPTL=("get" "set" "merge" "del" "help" "version" "output:" "stdin")
if ! OPT=$(getopt -o "$(printf "%s," "${OPTS[@]}")" -l "$(printf "%s," "${OPTL[@]}")" --  "${ARGUMENT[@]}"); then
    exit 1
fi

eval set -- "${OPT}"
unset OPT OPTS OPTL DEFAULT_ARGUMENT

while true; do
    case "${1}" in
        --get)
            mode="get"
            shift 1
            ;;
        --set)
            mode="set"
            shift 1
            ;;
        --merge)
            mode="merge"
            shift 1
            ;;
        --del)
            mode="del"
            shift 1
            ;;
        -h | --help)
            _usage
            exit 1
            ;;
        --output)
            output="${2}"
            shift 2
            ;;
        --version)
            _version
            exit 0
            ;;
        --stdin)
            stdin=true
            shift 1
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [[ "${mode}" = "none" ]]; then
    echo "One of --set|--get must be specified"
    exit 1
fi

file="${1=""}"
section="${2-""}"
param="${3-""}"
value="${4-""}"

export _crshini_debug=true

case "${mode}" in
    "get")
        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_get "${file}" "${section}" "${param}"
        ;;
    "set")
        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_set "${file}" "${section}" "${param}" "${value}"
        ;;
    "merge")
        _crshini_output="${output}" _crshini_stdin=true _crshini_merge "${file}" "${section}"
        ;;
    "del")
        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_del "${file}" "${section}" "${param}"
        ;;
esac
